# Generated by Django 5.1.6 on 2025-07-05 02:02

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SMSProvider',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('provider_code', models.CharField(choices=[('avrsms', 'AVRSMS (Default)'), ('hubtel', 'Hubtel (Ghana)'), ('africas_talking', "Africa's Talking (Pan-African)"), ('twilio', 'Twilio (Global)'), ('infobip', 'Infobip (Europe/Africa)'), ('termii', 'Termii (Nigeria)'), ('clickatell', 'Clickatell (Global)')], max_length=20, unique=True)),
                ('api_endpoint', models.URLField(default='https://api.avrsms.com/api/SendSMS')),
                ('supported_countries', models.JSONField(default=list, help_text='List of ISO country codes')),
                ('cost_per_sms', models.DecimalField(decimal_places=4, default=0.02, max_digits=6)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('is_active', models.BooleanField(default=True)),
                ('priority', models.IntegerField(default=1, help_text='1=highest priority')),
                ('configuration', models.JSONField(default=dict, help_text='API keys and settings')),
                ('daily_limit', models.IntegerField(default=10000, help_text='Daily SMS sending limit')),
                ('success_rate', models.DecimalField(decimal_places=2, default=95.0, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'SMS Provider',
                'verbose_name_plural': 'SMS Providers',
                'ordering': ['priority', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CommunicationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sms_enabled', models.BooleanField(default=True)),
                ('sms_order_updates', models.BooleanField(default=True)),
                ('sms_payment_notifications', models.BooleanField(default=True)),
                ('sms_price_alerts', models.BooleanField(default=False)),
                ('sms_weather_alerts', models.BooleanField(default=True)),
                ('sms_marketing', models.BooleanField(default=False)),
                ('email_enabled', models.BooleanField(default=True)),
                ('email_order_updates', models.BooleanField(default=True)),
                ('email_payment_notifications', models.BooleanField(default=True)),
                ('email_newsletters', models.BooleanField(default=False)),
                ('email_marketing', models.BooleanField(default=False)),
                ('whatsapp_enabled', models.BooleanField(default=False)),
                ('whatsapp_number', models.CharField(blank=True, max_length=20)),
                ('whatsapp_order_updates', models.BooleanField(default=False)),
                ('whatsapp_support', models.BooleanField(default=False)),
                ('push_enabled', models.BooleanField(default=True)),
                ('push_order_updates', models.BooleanField(default=True)),
                ('push_chat_messages', models.BooleanField(default=True)),
                ('push_marketing', models.BooleanField(default=False)),
                ('preferred_language', models.CharField(default='en', max_length=10)),
                ('timezone', models.CharField(default='Africa/Accra', max_length=50)),
                ('quiet_hours_start', models.TimeField(blank=True, null=True)),
                ('quiet_hours_end', models.TimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='communication_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Communication Preference',
                'verbose_name_plural': 'Communication Preferences',
            },
        ),
        migrations.CreateModel(
            name='SMSTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('template_type', models.CharField(choices=[('otp', 'OTP Verification'), ('order_confirmation', 'Order Confirmation'), ('payment_notification', 'Payment Notification'), ('delivery_update', 'Delivery Update'), ('price_alert', 'Price Alert'), ('weather_alert', 'Weather Alert'), ('marketing', 'Marketing Campaign'), ('reminder', 'Reminder'), ('welcome', 'Welcome Message'), ('password_reset', 'Password Reset')], max_length=30)),
                ('language', models.CharField(choices=[('en', 'English'), ('tw', 'Twi (Ghana)'), ('ga', 'Ga (Ghana)'), ('ee', 'Ewe (Ghana/Togo)'), ('ha', 'Hausa (West Africa)'), ('yo', 'Yoruba (Nigeria)'), ('ig', 'Igbo (Nigeria)'), ('sw', 'Swahili (East Africa)'), ('fr', 'French (West/Central Africa)'), ('ar', 'Arabic (North Africa)'), ('am', 'Amharic (Ethiopia)'), ('zu', 'Zulu (South Africa)'), ('xh', 'Xhosa (South Africa)'), ('af', 'Afrikaans (South Africa)'), ('pt', 'Portuguese (Angola/Mozambique)')], max_length=10)),
                ('country', models.CharField(blank=True, help_text='ISO country code', max_length=2)),
                ('subject', models.CharField(blank=True, max_length=160)),
                ('content', models.TextField(help_text='SMS content with variable placeholders {variable_name}')),
                ('variables', models.JSONField(default=list, help_text='List of variable names used in template')),
                ('character_count', models.IntegerField(editable=False)),
                ('is_default', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'SMS Template',
                'verbose_name_plural': 'SMS Templates',
                'ordering': ['template_type', 'language', 'name'],
                'unique_together': {('name', 'language', 'country')},
            },
        ),
        migrations.CreateModel(
            name='SMSMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('recipient_phone', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^\\+[1-9]\\d{1,14}$', 'Enter a valid international phone number')])),
                ('sender_id', models.CharField(default='AgriConnect', max_length=20)),
                ('message_type', models.CharField(max_length=30)),
                ('subject', models.CharField(blank=True, max_length=160)),
                ('content', models.TextField()),
                ('language', models.CharField(default='en', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('queued', 'Queued'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('failed', 'Failed'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('provider_message_id', models.CharField(blank=True, max_length=100)),
                ('provider_response', models.JSONField(default=dict)),
                ('failure_reason', models.TextField(blank=True)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('cost', models.DecimalField(decimal_places=4, default=0, max_digits=8)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('campaign_id', models.UUIDField(blank=True, null=True)),
                ('batch_id', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('provider', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='communications.smsprovider')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='communications.smstemplate')),
            ],
            options={
                'verbose_name': 'SMS Message',
                'verbose_name_plural': 'SMS Messages',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OTPCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phone_number', models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator('^\\+[1-9]\\d{1,14}$', 'Enter a valid international phone number')])),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('code', models.CharField(max_length=10)),
                ('purpose', models.CharField(choices=[('registration', 'Registration'), ('login', 'Login'), ('password_reset', 'Password Reset'), ('phone_verification', 'Phone Verification'), ('email_verification', 'Email Verification'), ('transaction', 'Transaction Confirmation'), ('order_confirmation', 'Order Confirmation'), ('payment_verification', 'Payment Verification'), ('profile_update', 'Profile Update')], max_length=30)),
                ('expires_at', models.DateTimeField()),
                ('attempts_count', models.IntegerField(default=0)),
                ('max_attempts', models.IntegerField(default=3)),
                ('is_used', models.BooleanField(default=False)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('metadata', models.JSONField(default=dict, help_text='Additional context data')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='communication_otp_codes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'OTP Code',
                'verbose_name_plural': 'OTP Codes',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['phone_number', 'purpose', 'expires_at'], name='communicati_phone_n_5aa3f9_idx'), models.Index(fields=['email', 'purpose', 'expires_at'], name='communicati_email_fdbd5d_idx')],
            },
        ),
        migrations.CreateModel(
            name='CommunicationLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('communication_type', models.CharField(choices=[('sms', 'SMS'), ('email', 'Email'), ('push', 'Push Notification'), ('whatsapp', 'WhatsApp'), ('ussd', 'USSD'), ('voice', 'Voice Call')], max_length=20)),
                ('recipient', models.CharField(help_text='Phone, email, or device ID', max_length=255)),
                ('purpose', models.CharField(max_length=30)),
                ('status', models.CharField(max_length=20)),
                ('content_snippet', models.TextField(help_text='First 200 chars of content', max_length=200)),
                ('cost', models.DecimalField(decimal_places=4, default=0, max_digits=8)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('sms_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='communications.smsmessage')),
            ],
            options={
                'verbose_name': 'Communication Log',
                'verbose_name_plural': 'Communication Logs',
                'ordering': ['-sent_at'],
                'indexes': [models.Index(fields=['user', 'communication_type'], name='communicati_user_id_76fa64_idx'), models.Index(fields=['sent_at'], name='communicati_sent_at_4cd97b_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='smsmessage',
            index=models.Index(fields=['recipient_phone', 'status'], name='communicati_recipie_b75031_idx'),
        ),
        migrations.AddIndex(
            model_name='smsmessage',
            index=models.Index(fields=['campaign_id'], name='communicati_campaig_25dad5_idx'),
        ),
        migrations.AddIndex(
            model_name='smsmessage',
            index=models.Index(fields=['created_at'], name='communicati_created_20e7ee_idx'),
        ),
    ]
