# Generated by Django 5.1.6 on 2025-07-08 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0001_initial'),
    ]

    operations = [
    ]
