# Generated by Django 5.1.6 on 2025-07-27 06:35

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0002_auto_20250708_1529'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='communicationlog',
            name='ai_content_generated',
            field=models.BooleanField(default=False, help_text='Whether content was AI-generated'),
        ),
        migrations.AddField(
            model_name='communicationlog',
            name='ai_enhanced',
            field=models.BooleanField(default=False, help_text='Whether AI was used to enhance this communication'),
        ),
        migrations.AddField(
            model_name='communicationlog',
            name='ai_model_used',
            field=models.CharField(blank=True, help_text='AI model used for processing', max_length=100),
        ),
        migrations.AddField(
            model_name='communicationlog',
            name='ai_optimization_score',
            field=models.FloatField(blank=True, help_text='AI-predicted engagement score (0-100)', null=True),
        ),
        migrations.AddField(
            model_name='communicationlog',
            name='ai_timing_optimized',
            field=models.BooleanField(default=False, help_text='Whether timing was AI-optimized'),
        ),
        migrations.AddField(
            model_name='communicationlog',
            name='ai_translated',
            field=models.BooleanField(default=False, help_text='Whether message was AI-translated'),
        ),
        migrations.AddField(
            model_name='communicationlog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='communicationlog',
            name='delivery_status',
            field=models.CharField(default='pending', help_text='Delivery status', max_length=20),
        ),
        migrations.AddField(
            model_name='communicationlog',
            name='engagement_score',
            field=models.FloatField(blank=True, help_text='Actual engagement score', null=True),
        ),
        migrations.AddField(
            model_name='communicationlog',
            name='message_content',
            field=models.TextField(blank=True, default='', help_text='Full message content'),
        ),
        migrations.AddField(
            model_name='communicationlog',
            name='message_type',
            field=models.CharField(default='general', help_text='Type of message', max_length=30),
        ),
        migrations.AddField(
            model_name='communicationlog',
            name='optimization_metadata',
            field=models.JSONField(default=dict, help_text='AI optimization metadata'),
        ),
        migrations.AddField(
            model_name='communicationlog',
            name='recipient_phone',
            field=models.CharField(blank=True, help_text='Recipient phone number', max_length=20),
        ),
        migrations.AddField(
            model_name='communicationlog',
            name='response_received',
            field=models.BooleanField(default=False, help_text='Whether farmer responded'),
        ),
        migrations.AddField(
            model_name='communicationlog',
            name='response_time_minutes',
            field=models.IntegerField(blank=True, help_text='Response time in minutes', null=True),
        ),
        migrations.AddField(
            model_name='communicationlog',
            name='sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_communications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='communicationlog',
            name='communication_type',
            field=models.CharField(choices=[('sms', 'SMS'), ('email', 'Email'), ('push', 'Push Notification'), ('whatsapp', 'WhatsApp'), ('ussd', 'USSD'), ('voice', 'Voice Call')], default='sms', max_length=20),
        ),
        migrations.AlterField(
            model_name='communicationlog',
            name='content_snippet',
            field=models.TextField(blank=True, help_text='First 200 chars of content', max_length=200),
        ),
        migrations.AlterField(
            model_name='communicationlog',
            name='purpose',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='communicationlog',
            name='sent_at',
            field=models.DateTimeField(blank=True, help_text='When the message was sent', null=True),
        ),
        migrations.AlterField(
            model_name='communicationlog',
            name='status',
            field=models.CharField(default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='AIMessageOptimization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('original_content', models.TextField(help_text='Original message content')),
                ('optimized_content', models.TextField(help_text='AI-optimized content')),
                ('message_type', models.CharField(help_text='Type of message', max_length=50)),
                ('farmer_profile', models.JSONField(help_text='Farmer profile used for optimization')),
                ('target_language', models.CharField(default='English', max_length=20)),
                ('ai_model_used', models.CharField(help_text='AI model used', max_length=100)),
                ('optimization_score', models.FloatField(help_text='AI-predicted engagement score')),
                ('processing_time_ms', models.IntegerField(help_text='Processing time in milliseconds')),
                ('actual_engagement', models.FloatField(blank=True, help_text='Actual engagement measured', null=True)),
                ('delivery_success', models.BooleanField(default=False)),
                ('read_confirmed', models.BooleanField(default=False)),
                ('response_received', models.BooleanField(default=False)),
                ('improvements_made', models.JSONField(default=list, help_text='List of improvements made by AI')),
                ('timing_optimized', models.BooleanField(default=False)),
                ('optimal_send_time', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'ai_message_optimization',
                'indexes': [models.Index(fields=['message_type', 'created_at'], name='ai_message__message_ce1111_idx'), models.Index(fields=['ai_model_used'], name='ai_message__ai_mode_e0bdca_idx'), models.Index(fields=['optimization_score'], name='ai_message__optimiz_cdb6c7_idx')],
            },
        ),
        migrations.CreateModel(
            name='AITranslationCache',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_text_hash', models.CharField(help_text='SHA256 hash of source text', max_length=64)),
                ('source_language', models.CharField(default='English', max_length=20)),
                ('target_language', models.CharField(max_length=20)),
                ('context_type', models.CharField(help_text='Agricultural context type', max_length=50)),
                ('source_text', models.TextField()),
                ('translated_text', models.TextField()),
                ('confidence_score', models.FloatField()),
                ('ai_model_used', models.CharField(max_length=100)),
                ('times_used', models.IntegerField(default=1)),
                ('last_used', models.DateTimeField(auto_now=True)),
                ('human_approved', models.BooleanField(blank=True, null=True)),
                ('quality_score', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'ai_translation_cache',
                'indexes': [models.Index(fields=['source_text_hash'], name='ai_translat_source__cbfb77_idx'), models.Index(fields=['target_language'], name='ai_translat_target__2c72c6_idx'), models.Index(fields=['times_used'], name='ai_translat_times_u_0625bf_idx')],
                'unique_together': {('source_text_hash', 'target_language', 'context_type')},
            },
        ),
        migrations.CreateModel(
            name='CommunicationAnalytics',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('period_start', models.DateTimeField()),
                ('period_end', models.DateTimeField()),
                ('period_type', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='daily', max_length=20)),
                ('total_messages_sent', models.IntegerField(default=0)),
                ('ai_enhanced_messages', models.IntegerField(default=0)),
                ('delivery_success_rate', models.FloatField(default=0.0)),
                ('engagement_rate', models.FloatField(default=0.0)),
                ('avg_optimization_score', models.FloatField(blank=True, null=True)),
                ('ai_accuracy_rate', models.FloatField(blank=True, null=True)),
                ('avg_processing_time_ms', models.FloatField(blank=True, null=True)),
                ('message_type_stats', models.JSONField(default=dict, help_text='Performance by message type')),
                ('best_sending_hours', models.JSONField(default=list, help_text='Most effective sending hours')),
                ('engagement_by_hour', models.JSONField(default=dict, help_text='Engagement rates by hour')),
                ('model_performance_stats', models.JSONField(default=dict, help_text='Performance by AI model')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'communication_analytics',
                'indexes': [models.Index(fields=['period_start', 'period_end'], name='communicati_period__c5ede4_idx'), models.Index(fields=['period_type'], name='communicati_period__8e8b3d_idx')],
                'unique_together': {('period_start', 'period_end', 'period_type')},
            },
        ),
        migrations.CreateModel(
            name='FarmerCommunicationProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('farmer_id', models.IntegerField(help_text='Reference to farmer', unique=True)),
                ('preferred_message_length', models.CharField(choices=[('short', 'Short (< 80 chars)'), ('medium', 'Medium (80-160 chars)'), ('long', 'Long (> 160 chars)')], default='medium', max_length=20)),
                ('preferred_communication_times', models.JSONField(default=list, help_text='Preferred hours for receiving messages')),
                ('language_complexity_level', models.CharField(choices=[('simple', 'Simple'), ('medium', 'Medium'), ('advanced', 'Advanced')], default='medium', max_length=20)),
                ('average_response_time_minutes', models.FloatField(blank=True, null=True)),
                ('engagement_rate', models.FloatField(default=0.0, help_text='Overall engagement rate (0-100)')),
                ('preferred_message_types', models.JSONField(default=list, help_text='Message types that get best engagement')),
                ('ai_optimization_enabled', models.BooleanField(default=True)),
                ('timing_optimization_enabled', models.BooleanField(default=True)),
                ('content_personalization_enabled', models.BooleanField(default=True)),
                ('total_messages_received', models.IntegerField(default=0)),
                ('total_responses_sent', models.IntegerField(default=0)),
                ('last_engagement_analysis', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'farmer_communication_profile',
                'indexes': [models.Index(fields=['farmer_id'], name='farmer_comm_farmer__1e6c5c_idx'), models.Index(fields=['engagement_rate'], name='farmer_comm_engagem_75c4df_idx')],
            },
        ),
        migrations.CreateModel(
            name='IntelligentResponse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('incoming_message', models.TextField(help_text='Original farmer message')),
                ('farmer_id', models.IntegerField(help_text='Farmer who sent the message')),
                ('message_language', models.CharField(default='English', max_length=20)),
                ('detected_intent', models.CharField(help_text='AI-detected intent', max_length=100)),
                ('urgency_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=20)),
                ('topic_category', models.CharField(help_text='Message topic category', max_length=50)),
                ('ai_response', models.TextField(help_text='AI-generated response')),
                ('confidence_score', models.FloatField(help_text='AI confidence in response (0-100)')),
                ('requires_human_intervention', models.BooleanField(default=False)),
                ('ai_model_used', models.CharField(max_length=100)),
                ('processing_time_ms', models.IntegerField()),
                ('response_sent', models.BooleanField(default=False)),
                ('farmer_satisfied', models.BooleanField(blank=True, null=True)),
                ('escalated_to_human', models.BooleanField(default=False)),
                ('follow_up_needed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'intelligent_response',
                'indexes': [models.Index(fields=['farmer_id', 'created_at'], name='intelligent_farmer__66c6c7_idx'), models.Index(fields=['detected_intent'], name='intelligent_detecte_1dc6a1_idx'), models.Index(fields=['urgency_level'], name='intelligent_urgency_339fad_idx')],
            },
        ),
    ]
