# Generated by Django 5.1.6 on 2025-07-06 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentgateway',
            name='name',
            field=models.CharField(choices=[('paystack', 'Paystack'), ('flutterwave', 'Flutterwave'), ('mtn_momo', 'MTN Mobile Money'), ('vodafone_cash', 'Vodafone Cash'), ('airteltigo_money', 'AirtelTigo Money'), ('bank_transfer', 'Bank Transfer'), ('stripe', 'Stripe'), ('bitcoin_core', 'Bitcoin Core'), ('usdc_polygon', 'USDC on Polygon'), ('ethereum_mainnet', 'Ethereum Mainnet'), ('agri_credit_bank', 'Agricultural Credit Bank'), ('farmer_finance_coop', 'Farmer Finance Cooperative'), ('digital_agri_lending', 'Digital Agricultural Lending')], max_length=50, unique=True),
        ),
    ]
