# Generated by Django 5.1.6 on 2025-07-06 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_alter_paymentgateway_name'),
    ]

    operations = [
    ]
