# Generated by Django 5.1.6 on 2025-08-03 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_fix_transaction_fee_precision'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentgateway',
            name='transaction_fee_percentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
