# Generated by Django 5.1.6 on 2025-08-03 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_alter_paymentgateway_transaction_fee_percentage'),
    ]

    operations = [
    ]
