name: agritrade-backend
services:
  - name: web
    source_dir: /
    github:
      repo: ckbsinnogate/agritrade-backend
      branch: main
      deploy_on_push: true
    build_command: |
      python -m pip install --upgrade pip
      pip install -r requirements.txt
    run_command: |
      python manage.py migrate --noinput
      gunicorn --worker-tmp-dir /dev/shm myapiproject.wsgi:application --bind 0.0.0.0:8080 --workers 2
    environment_slug: python
    instance_count: 1
    instance_size_slug: basic-xxs
    http_port: 8080
    health_check:
      http_path: /api/health/
    routes:
      - path: /
    envs:
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: ".ondigitalocean.app,agritrade-backend.ondigitalocean.app"
      - key: CORS_ALLOWED_ORIGINS
        value: "https://agritrade-frontend.ondigitalocean.app"
      - key: DJANGO_SETTINGS_MODULE
        value: "myapiproject.settings_appplatform"
      - key: DISABLE_COLLECTSTATIC
        value: "1"
      - key: SECRET_KEY
        scope: RUN_AND_BUILD_TIME
        type: SECRET
      - key: OPENAI_API_KEY
        value: "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"
      - key: OPENAI_BASE_URL
        value: "https://openrouter.ai/api/v1"
      - key: OPENAI_MODEL
        value: "anthropic/claude-3-haiku:beta"
      - key: WEATHER_API_KEY
        value: ""
    databases:
      - name: agritrade-db

databases:
  - name: agritrade-db
    engine: PG
    size: basic-xs
    version: "15"
    production: true