name: agritrade-backend
services:
  - name: web
    source_dir: /
    github:
      repo: your-username/agritrade-backend
      branch: main
      deploy_on_push: true
    run_command: |
      python manage.py migrate --noinput
      python manage.py collectstatic --noinput
      gunicorn --worker-tmp-dir /dev/shm myapiproject.wsgi:application --bind 0.0.0.0:8080 --workers 2
    build_command: |
      python -m pip install --upgrade pip
      pip install -r requirements.txt
    environment_slug: python
    instance_count: 1
    instance_size_slug: basic-xxs
    http_port: 8080
    health_check:
      http_path: /api/health/
    routes:
      - path: /
    envs:
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: ".ondigitalocean.app,agritrade-backend.ondigitalocean.app"
      - key: CORS_ALLOWED_ORIGINS
        value: "https://agritrade-frontend.ondigitalocean.app"
      - key: SECRET_KEY
        scope: RUN_AND_BUILD_TIME
        type: SECRET
      - key: DATABASE_URL
        scope: RUN_AND_BUILD_TIME
        type: SECRET

databases:
  - name: agritrade-db
    engine: PG
    size: basic-xs
    version: "15"
    production: true

static_sites:
  - name: admin-static
    source_dir: staticfiles
    routes:
      - path: /static
