# Generated by Django 5.1.6 on 2025-07-31 20:22

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessingEquipment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('equipment_type', models.CharField(choices=[('milling', 'Milling Equipment'), ('processing', 'Processing Equipment'), ('packaging', 'Packaging Equipment'), ('cleaning', 'Cleaning Equipment'), ('storage', 'Storage Equipment'), ('transport', 'Transport Equipment')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('model_number', models.CharField(blank=True, max_length=100)),
                ('manufacturer', models.CharField(blank=True, max_length=100)),
                ('capacity', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('capacity_unit', models.CharField(default='kg', max_length=20)),
                ('status', models.CharField(choices=[('available', 'Available'), ('in_use', 'In Use'), ('maintenance', 'Under Maintenance'), ('broken', 'Broken'), ('reserved', 'Reserved')], default='available', max_length=20)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('last_maintenance', models.DateTimeField(blank=True, null=True)),
                ('next_maintenance', models.DateTimeField(blank=True, null=True)),
                ('operating_hours', models.PositiveIntegerField(default=0)),
                ('specifications', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('processor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processing_equipment', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'processing_equipment',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProcessingSchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('scheduled_start', models.DateTimeField()),
                ('scheduled_end', models.DateTimeField()),
                ('actual_start', models.DateTimeField(blank=True, null=True)),
                ('actual_end', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('delayed', 'Delayed')], default='scheduled', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=10)),
                ('raw_materials', models.JSONField(blank=True, default=list)),
                ('expected_output', models.JSONField(blank=True, default=dict)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('equipment_required', models.ManyToManyField(blank=True, to='processing.processingequipment')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.order')),
                ('processor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processing_schedules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'processing_schedule',
                'ordering': ['scheduled_start'],
            },
        ),
        migrations.CreateModel(
            name='ProcessingQualityCheck',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('check_type', models.CharField(choices=[('incoming', 'Incoming Materials'), ('in_process', 'In-Process'), ('final', 'Final Product'), ('packaging', 'Packaging'), ('storage', 'Storage')], max_length=20)),
                ('check_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('product_batch', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('passed', 'Passed'), ('failed', 'Failed'), ('requires_recheck', 'Requires Recheck')], default='pending', max_length=20)),
                ('quality_score', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('parameters_checked', models.JSONField(blank=True, default=list)),
                ('test_results', models.JSONField(blank=True, default=dict)),
                ('issues_found', models.TextField(blank=True)),
                ('corrective_actions', models.TextField(blank=True)),
                ('compliance_standards', models.JSONField(blank=True, default=list)),
                ('attachments', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('inspector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conducted_checks', to=settings.AUTH_USER_MODEL)),
                ('processor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quality_checks', to=settings.AUTH_USER_MODEL)),
                ('schedule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='processing.processingschedule')),
            ],
            options={
                'db_table': 'processing_quality_checks',
                'ordering': ['-check_date'],
            },
        ),
        migrations.CreateModel(
            name='ProcessingStats',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('total_orders_processed', models.PositiveIntegerField(default=0)),
                ('total_volume_processed', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('volume_unit', models.CharField(default='kg', max_length=20)),
                ('equipment_utilization', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('quality_pass_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('production_efficiency', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('revenue_generated', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('costs_incurred', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('profit_margin', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('energy_consumption', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('waste_generated', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('downtime_hours', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('metrics_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('processor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processing_stats', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'processing_stats',
                'ordering': ['-date'],
                'unique_together': {('processor', 'date')},
            },
        ),
    ]
