# Generated by Django 5.1.6 on 2025-08-06 04:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FarmerDashboardPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_currency', models.CharField(default='GHS', max_length=3)),
                ('preferred_language', models.CharField(default='en', max_length=10)),
                ('dashboard_theme', models.CharField(choices=[('light', 'Light'), ('dark', 'Dark'), ('auto', 'Auto')], default='light', max_length=20)),
                ('weather_alerts', models.BooleanField(default=True)),
                ('market_price_alerts', models.BooleanField(default=True)),
                ('order_notifications', models.BooleanField(default=True)),
                ('payment_reminders', models.BooleanField(default=True)),
                ('show_revenue_trends', models.BooleanField(default=True)),
                ('show_crop_analytics', models.BooleanField(default=True)),
                ('show_market_insights', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('farmer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Farmer Dashboard Preference',
                'verbose_name_plural': 'Farmer Dashboard Preferences',
            },
        ),
        migrations.CreateModel(
            name='FarmerGoal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('goal_type', models.CharField(choices=[('revenue', 'Revenue Target'), ('production', 'Production Volume'), ('customers', 'Customer Acquisition'), ('farms', 'Farm Expansion'), ('sustainability', 'Sustainability Goal')], max_length=20)),
                ('target_value', models.DecimalField(decimal_places=2, max_digits=15)),
                ('current_value', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('unit', models.CharField(default='GHS', max_length=50)),
                ('start_date', models.DateField()),
                ('target_date', models.DateField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('paused', 'Paused'), ('cancelled', 'Cancelled')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Farmer Goal',
                'verbose_name_plural': 'Farmer Goals',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FarmerAlert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('alert_type', models.CharField(choices=[('weather', 'Weather Alert'), ('market', 'Market Price Alert'), ('inventory', 'Inventory Alert'), ('order', 'Order Update'), ('payment', 'Payment Reminder'), ('crop', 'Crop Advisory'), ('general', 'General Notice')], max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=10)),
                ('is_read', models.BooleanField(default=False)),
                ('is_archived', models.BooleanField(default=False)),
                ('related_product_id', models.CharField(blank=True, max_length=100, null=True)),
                ('related_order_id', models.CharField(blank=True, max_length=100, null=True)),
                ('related_farm_id', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Farmer Alert',
                'verbose_name_plural': 'Farmer Alerts',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['farmer', 'is_read'], name='farmer_dash_farmer__1c1b11_idx'), models.Index(fields=['alert_type', 'priority'], name='farmer_dash_alert_t_fb643b_idx'), models.Index(fields=['created_at'], name='farmer_dash_created_804920_idx')],
            },
        ),
        migrations.CreateModel(
            name='FarmerDashboardMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('orders_count', models.IntegerField(default=0)),
                ('products_sold', models.IntegerField(default=0)),
                ('average_order_value', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_products', models.IntegerField(default=0)),
                ('active_products', models.IntegerField(default=0)),
                ('low_stock_products', models.IntegerField(default=0)),
                ('out_of_stock_products', models.IntegerField(default=0)),
                ('new_customers', models.IntegerField(default=0)),
                ('returning_customers', models.IntegerField(default=0)),
                ('total_customers', models.IntegerField(default=0)),
                ('farms_registered', models.IntegerField(default=0)),
                ('total_farm_area', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_metrics', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Farmer Dashboard Metric',
                'verbose_name_plural': 'Farmer Dashboard Metrics',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['farmer', 'date'], name='farmer_dash_farmer__229c1a_idx'), models.Index(fields=['date'], name='farmer_dash_date_4487aa_idx')],
                'unique_together': {('farmer', 'date')},
            },
        ),
    ]
