# Generated by Django 5.1.6 on 2025-08-22 02:53

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanApplication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('loan_type', models.CharField(choices=[('seasonal_loan', 'Seasonal Farming Loan'), ('equipment_financing', 'Equipment Financing'), ('working_capital', 'Working Capital'), ('harvest_advance', 'Harvest Advance'), ('microfinance', 'Microfinance'), ('group_lending', 'Group Lending'), ('instant_advance', 'Instant Advance'), ('contract_financing', 'Contract Financing'), ('supply_chain_credit', 'Supply Chain Credit')], max_length=30)),
                ('amount_requested', models.DecimalField(decimal_places=2, max_digits=12)),
                ('amount_approved', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('interest_rate', models.DecimalField(decimal_places=2, default=Decimal('15.00'), max_digits=5)),
                ('term_months', models.PositiveIntegerField(default=12)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('disbursed', 'Disbursed'), ('rejected', 'Rejected'), ('repaid', 'Fully Repaid'), ('defaulted', 'Defaulted')], default='pending', max_length=20)),
                ('application_date', models.DateTimeField(auto_now_add=True)),
                ('approval_date', models.DateTimeField(blank=True, null=True)),
                ('disbursement_date', models.DateTimeField(blank=True, null=True)),
                ('repayment_start_date', models.DateField(blank=True, null=True)),
                ('maturity_date', models.DateField(blank=True, null=True)),
                ('purpose', models.TextField()),
                ('collateral_description', models.TextField(blank=True)),
                ('business_plan', models.TextField(blank=True)),
                ('credit_score', models.PositiveIntegerField(blank=True, null=True)),
                ('monthly_income', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('existing_debts', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('reviewer_notes', models.TextField(blank=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_applications', to=settings.AUTH_USER_MODEL)),
                ('financial_partner', models.ForeignKey(limit_choices_to={'roles__name': 'FINANCIAL_PARTNER'}, on_delete=django.db.models.deletion.CASCADE, related_name='managed_loans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'financial_loan_applications',
                'ordering': ['-application_date'],
            },
        ),
        migrations.CreateModel(
            name='LoanRepayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('due_date', models.DateField()),
                ('amount_due', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('payment_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('paid', 'Paid'), ('overdue', 'Overdue'), ('partial', 'Partial Payment')], default='scheduled', max_length=20)),
                ('transaction_reference', models.CharField(blank=True, max_length=100)),
                ('payment_method', models.CharField(blank=True, max_length=50)),
                ('late_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('loan_application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repayments', to='financial.loanapplication')),
            ],
            options={
                'db_table': 'financial_loan_repayments',
                'ordering': ['due_date'],
            },
        ),
        migrations.CreateModel(
            name='FinancialStats',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('period_type', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('yearly', 'Yearly')], max_length=20)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('total_loans_issued', models.PositiveIntegerField(default=0)),
                ('total_loan_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('active_loans_count', models.PositiveIntegerField(default=0)),
                ('active_loans_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('repaid_loans_count', models.PositiveIntegerField(default=0)),
                ('repaid_loans_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('defaulted_loans_count', models.PositiveIntegerField(default=0)),
                ('defaulted_loans_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('total_investments_count', models.PositiveIntegerField(default=0)),
                ('total_investment_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('active_investments_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('total_returns', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('average_loan_size', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('loan_approval_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('average_interest_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('portfolio_return_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('calculated_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('financial_partner', models.ForeignKey(limit_choices_to={'roles__name': 'FINANCIAL_PARTNER'}, on_delete=django.db.models.deletion.CASCADE, related_name='financial_stats', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'financial_stats',
                'ordering': ['-period_start'],
                'indexes': [models.Index(fields=['period_type'], name='financial_s_period__65369c_idx'), models.Index(fields=['period_start'], name='financial_s_period__1a8ccb_idx'), models.Index(fields=['financial_partner'], name='financial_s_financi_1e7a53_idx')],
                'unique_together': {('financial_partner', 'period_type', 'period_start')},
            },
        ),
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('investment_type', models.CharField(choices=[('agricultural_project', 'Agricultural Project'), ('farmer_loan_portfolio', 'Farmer Loan Portfolio'), ('supply_chain_financing', 'Supply Chain Financing'), ('equipment_leasing', 'Equipment Leasing'), ('crop_insurance', 'Crop Insurance'), ('commodity_trading', 'Commodity Trading')], max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('principal_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('current_value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('expected_return_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('actual_return_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('investment_date', models.DateField()),
                ('maturity_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('matured', 'Matured'), ('liquidated', 'Liquidated'), ('suspended', 'Suspended')], default='active', max_length=20)),
                ('risk_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('investor', models.ForeignKey(limit_choices_to={'roles__name': 'FINANCIAL_PARTNER'}, on_delete=django.db.models.deletion.CASCADE, related_name='investments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'financial_investments',
                'ordering': ['-investment_date'],
                'indexes': [models.Index(fields=['status'], name='financial_i_status_1e9a0d_idx'), models.Index(fields=['investment_type'], name='financial_i_investm_2c5992_idx'), models.Index(fields=['investor'], name='financial_i_investo_6ad1ee_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='loanapplication',
            index=models.Index(fields=['status'], name='financial_l_status_e54edd_idx'),
        ),
        migrations.AddIndex(
            model_name='loanapplication',
            index=models.Index(fields=['loan_type'], name='financial_l_loan_ty_ce95c4_idx'),
        ),
        migrations.AddIndex(
            model_name='loanapplication',
            index=models.Index(fields=['financial_partner'], name='financial_l_financi_600189_idx'),
        ),
        migrations.AddIndex(
            model_name='loanapplication',
            index=models.Index(fields=['application_date'], name='financial_l_applica_34d388_idx'),
        ),
        migrations.AddIndex(
            model_name='loanrepayment',
            index=models.Index(fields=['status'], name='financial_l_status_ab925b_idx'),
        ),
        migrations.AddIndex(
            model_name='loanrepayment',
            index=models.Index(fields=['due_date'], name='financial_l_due_dat_7bb81d_idx'),
        ),
        migrations.AddIndex(
            model_name='loanrepayment',
            index=models.Index(fields=['loan_application'], name='financial_l_loan_ap_79362e_idx'),
        ),
    ]
