# Generated by Django 5.1.6 on 2025-07-05 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrole',
            name='name',
            field=models.CharField(choices=[('FARMER', 'Farmer'), ('PROCESSOR', 'Processor'), ('CONSUMER', 'Consumer'), ('INSTITUTION', 'Institution'), ('WAREHOUSE_MANAGER', 'Warehouse Manager'), ('QUALITY_INSPECTOR', 'Quality Inspector'), ('LOGISTICS_PARTNER', 'Logistics Partner'), ('AGENT', 'Sales Agent/Field Officer'), ('FINANCIAL_PARTNER', 'Financial Partner'), ('GOVERNMENT_OFFICIAL', 'Government Official'), ('ADMIN', 'Administrator')], max_length=50, unique=True),
        ),
    ]
