# Generated by Django 5.1.6 on 2025-08-04 02:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_userrole_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailOTP',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('otp_code', models.CharField(db_index=True, max_length=10)),
                ('purpose', models.CharField(choices=[('registration', 'Registration'), ('login', 'Login Verification'), ('password_reset', 'Password Reset'), ('email_verification', 'Email Verification'), ('account_security', 'Account Security'), ('profile_update', 'Profile Update'), ('sensitive_action', 'Sensitive Action')], default='registration', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('expired', 'Expired'), ('failed', 'Failed'), ('blocked', 'Blocked')], default='pending', max_length=10)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('session_key', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('attempts_count', models.PositiveIntegerField(default=0)),
                ('max_attempts', models.PositiveIntegerField(default=3)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='email_otps', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'email_otps',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmailOTPAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempted_code', models.CharField(max_length=10)),
                ('is_successful', models.BooleanField(default=False)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('attempted_at', models.DateTimeField(auto_now_add=True)),
                ('response_time_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('failure_reason', models.CharField(blank=True, max_length=100)),
                ('email_otp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='authentication.emailotp')),
            ],
            options={
                'db_table': 'email_otp_attempts',
                'ordering': ['-attempted_at'],
            },
        ),
        migrations.CreateModel(
            name='EmailOTPRateLimit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('purpose', models.CharField(db_index=True, max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, db_index=True, null=True)),
                ('daily_count', models.PositiveIntegerField(default=0)),
                ('hourly_count', models.PositiveIntegerField(default=0)),
                ('first_request_today', models.DateTimeField(auto_now_add=True)),
                ('last_request_at', models.DateTimeField(auto_now=True)),
                ('reset_date', models.DateField(auto_now_add=True)),
                ('is_blocked', models.BooleanField(default=False)),
                ('blocked_until', models.DateTimeField(blank=True, null=True)),
                ('block_reason', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'db_table': 'email_otp_rate_limits',
                'indexes': [models.Index(fields=['email', 'purpose'], name='email_otp_r_email_b88afc_idx'), models.Index(fields=['ip_address', 'last_request_at'], name='email_otp_r_ip_addr_2ee36f_idx'), models.Index(fields=['is_blocked', 'blocked_until'], name='email_otp_r_is_bloc_97d3a8_idx')],
                'unique_together': {('email', 'purpose')},
            },
        ),
        migrations.AddIndex(
            model_name='emailotp',
            index=models.Index(fields=['email', 'purpose', 'status'], name='email_otps_email_b6b6c6_idx'),
        ),
        migrations.AddIndex(
            model_name='emailotp',
            index=models.Index(fields=['otp_code', 'status'], name='email_otps_otp_cod_85121e_idx'),
        ),
        migrations.AddIndex(
            model_name='emailotp',
            index=models.Index(fields=['expires_at', 'status'], name='email_otps_expires_949185_idx'),
        ),
        migrations.AddIndex(
            model_name='emailotp',
            index=models.Index(fields=['created_at'], name='email_otps_created_5102ba_idx'),
        ),
        migrations.AddIndex(
            model_name='emailotpattempt',
            index=models.Index(fields=['email_otp', 'attempted_at'], name='email_otp_a_email_o_863adf_idx'),
        ),
        migrations.AddIndex(
            model_name='emailotpattempt',
            index=models.Index(fields=['is_successful', 'attempted_at'], name='email_otp_a_is_succ_c8008f_idx'),
        ),
    ]
