# Generated by Django 5.1.6 on 2025-08-16 05:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('latitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('region', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'unique_together': {('name', 'region')},
            },
        ),
        migrations.CreateModel(
            name='WeatherAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('rainfall', 'Rainfall'), ('temperature', 'Temperature'), ('drought', 'Drought'), ('flood', 'Flood'), ('storm', 'Storm'), ('general', 'General')], max_length=20)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=10)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('recommendations', models.JSONField(default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weather.weatherlocation')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CurrentWeather',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.DecimalField(decimal_places=2, max_digits=5)),
                ('humidity', models.DecimalField(decimal_places=2, max_digits=5)),
                ('weather_condition', models.CharField(max_length=100)),
                ('rainfall_prediction', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('wind_speed', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('pressure', models.DecimalField(decimal_places=2, default=1013.25, max_digits=7)),
                ('visibility', models.DecimalField(decimal_places=2, default=10, max_digits=5)),
                ('uv_index', models.IntegerField(default=5)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weather.weatherlocation')),
            ],
            options={
                'ordering': ['-last_updated'],
            },
        ),
        migrations.CreateModel(
            name='WeatherForecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forecast_date', models.DateField()),
                ('temp_high', models.DecimalField(decimal_places=2, max_digits=5)),
                ('temp_low', models.DecimalField(decimal_places=2, max_digits=5)),
                ('condition', models.CharField(max_length=100)),
                ('rainfall_probability', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weather.weatherlocation')),
            ],
            options={
                'ordering': ['forecast_date'],
                'unique_together': {('location', 'forecast_date')},
            },
        ),
    ]
