# Generated by Django 5.1.6 on 2025-08-03 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='warehouseinventory',
            name='quantity',
        ),
    ]
