# Generated by Django 5.1.6 on 2025-08-03 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouses', '0002_remove_warehouseinventory_quantity'),
    ]

    operations = [
    ]
